akka {
  cluster {
    seed-nodes = [
      "akka.tcp://essent@127.0.0.1:2551",
      "akka.tcp://essent@127.0.0.1:2552"]

    min-nr-of-members = 3
    role {
      core.min-nr-of-members = 2
      external.min-nr-of-members = 1
    }
    metrics.enabled = off
    # auto-down-unreachable-after = 10s
  }
  actor {
    provider = "akka.cluster.ClusterActorRefProvider"
    deployment {
      /abn-amro/creditRouter = {
        router = adaptive-group
        # metrics-selector = heap
        # metrics-selector = load
        # metrics-selector = cpu
        metrics-selector = mix
        nr-of-instances = 1
        routees.paths = ["/user/credit"]
        cluster {
          enabled = on
          use-role = external
          allow-local-routees = off
        }
      }
    }
  }
  remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }
  }
//  loglevel = DEBUG
//  debug {
//    receive = on
//  }
//  log-dead-letters = off
}

